// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: organisation.sql

package db

import (
	"context"
	"database/sql"
)

const createOrganisation = `-- name: CreateOrganisation :one
INSERT INTO organisations (name, owner)
VALUES ($1, $2) 
RETURNING id, name, owner, created_at, updated_at
`

type CreateOrganisationParams struct {
	Name  sql.NullString `json:"name"`
	Owner int64          `json:"owner"`
}

func (q *Queries) CreateOrganisation(ctx context.Context, arg CreateOrganisationParams) (Organisation, error) {
	row := q.db.QueryRowContext(ctx, createOrganisation, arg.Name, arg.Owner)
	var i Organisation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Owner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrganisation = `-- name: DeleteOrganisation :exec
DELETE FROM organisations
WHERE id = $1
`

func (q *Queries) DeleteOrganisation(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteOrganisation, id)
	return err
}

const getOrganisation = `-- name: GetOrganisation :one
SELECT id, name, owner, created_at, updated_at FROM organisations
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrganisation(ctx context.Context, id int64) (Organisation, error) {
	row := q.db.QueryRowContext(ctx, getOrganisation, id)
	var i Organisation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Owner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrganisation = `-- name: ListOrganisation :many
SELECT id, name, owner, created_at, updated_at FROM organisations
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListOrganisationParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListOrganisation(ctx context.Context, arg ListOrganisationParams) ([]Organisation, error) {
	rows, err := q.db.QueryContext(ctx, listOrganisation, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organisation
	for rows.Next() {
		var i Organisation
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Owner,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganisation = `-- name: UpdateOrganisation :one
UPDATE organisations
SET name = $2
WHERE id = $1
RETURNING id, name, owner, created_at, updated_at
`

type UpdateOrganisationParams struct {
	ID   int64          `json:"id"`
	Name sql.NullString `json:"name"`
}

func (q *Queries) UpdateOrganisation(ctx context.Context, arg UpdateOrganisationParams) (Organisation, error) {
	row := q.db.QueryRowContext(ctx, updateOrganisation, arg.ID, arg.Name)
	var i Organisation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Owner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
